# 应用名称
server:
  port: 10602
  servlet:
    context-path: /redis
# 启动时需要配置 秘钥
# 方案一：在yml中加这个密钥的配置，在项目启动的时候，会根据密钥自动解密ENC(加密串)所代表的数据信息
# 方案二：将秘钥加入启动参数 -Djasypt.encryptor.password=xxx
jasypt:
  encryptor:
    password: phoenix
spring:
  # redis 配置
  redis:
    # 地址
    host: www.bytes-space.com
    # 端口，默认为6379
    port: 10379
    database: 0
    # 密码
    password: ENC(PfDPA+y3YVDqtcZ0XvkPjL6AYJse5+da)
    # 连接超时时间
    timeout: 20s
#    jedis:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 10
#        # 连接池中的最大空闲连接
#        max-idle: 30
#        # 连接池的最大数据库连接数
#        max-active: 100
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池中的最大空闲连接
        max-idle: 30
        # 连接池的最大数据库连接数
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
