server:
  port: 8089
  servlet:
    context-path: /

logging:
  level:
    com.example: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.113.229:3306/pigxx
    username: root
    password: 123456
#    url: jdbc:mysql://112.86.147.133:3322/hospital_online_admin?useSSL=false&allowMultiQueries=true&serverTimezone=GMT&autoReconnect=true&failOverReadOnly=false
#    username: root
#    password: njzhyl123qwerz
  application:
    name: redis-service
#    type: com.zaxxer.hikari.HikariDataSource

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
mybatis:
  #  通用mapper自动开启驼峰
  #  configuration:
  #    map-underscore-to-camel-case: true
  type-aliases-package: com.example.demo.pojo
#  mapper-locations: mapper/*.xml
