server:
  port: 9354

spring:
  thymeleaf:
    # 默认为true，关闭thymeleaf缓存
    cache: false
  # 数据源配置
  datasource:
    username: root
    password: centos123qwer
    url: jdbc:mysql://www.bytes-space.com:63306/spring_security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    # mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver

mine:
  security:
    authentication:
      loginPage: /login/page # 响应认证（登录）页面的url
      loginProcessingUrl: /login/form # 登录表单提交处理的url
      usernameParameter: username # 登录表单提交的用户名的属性名
      passwordParameter: password # 登录表单提交的密码的属性名
      staticPath: # 静态资源路径 /dist/** /modules/** /plugins/**
        - /dist/**
        - /modules/**
        - /plugins/**
      loginReturnType: REDIRECT # 认证之后 响应的类型 JSON/REDIRECT