server:
  port: 9354
  servlet:
    session:
      # session会话默认超时时间，默认是30分钟 30，最小为1分钟 1m
      timeout: 2h
      cookie:
        name: JSESSIONID # 指定浏览器cookie中关于SessionID保存的名称；默认为JSESSIONID，store-type为redis时，默认为SESSION

spring:
  session:
    # store-type: none 默认服务器存储session，前端cookie中的key为JSESSIONID
    # store-type: redis 使用redis存储session，前端cookie中的key为SESSION
    # 需要统一session名称
    store-type: redis # 使用redis存储session
  thymeleaf:
    # 默认为true，关闭thymeleaf缓存
    cache: false
  # 数据源配置
  datasource:
    username: root
    password: centos123qwer
    url: jdbc:mysql://www.bytes-space.com:10306/spring_security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    # mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis 配置
  redis:
    # 地址
    host: www.bytes-space.com
    # 端口，默认为6379
    port: 10379
    database: 2
    # 密码
    password: centos123qwer
    # 连接超时时间
    timeout: 20s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池中的最大空闲连接
        max-idle: 30
        # 连接池的最大数据库连接数
        max-active: 100
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
mine:
  security:
    authentication:
      loginPage: /login/page # 响应认证（登录）页面的url
      loginProcessingUrl: /login/form # 登录表单提交处理的url
      usernameParameter: username # 登录表单提交的用户名的属性名
      passwordParameter: password # 登录表单提交的密码的属性名
      staticPath: # 静态资源路径 /dist/** /modules/** /plugins/**
        - /favicon.ico
        - /dist/**
        - /modules/**
        - /plugins/**
      loginReturnType: REDIRECT # 认证之后 响应的类型 JSON/REDIRECT
      imageCodeUrl: /code/image # 获取图形验证码地址
      mobileCodeUrl: /code/mobile #发送手机验证码地址
      mobilePage: /mobile/page # 前往手机登录页面
      # 60*60*24*7 7天
      tokenValiditySeconds: 604800 # 记住我功能有效时长