# 应用名称
server:
  port: 10201
  servlet:
    context-path: /valid
# 启动时需要配置 秘钥
# 方案一：在yml中加这个密钥的配置，在项目启动的时候，会根据密钥自动解密ENC(加密串)所代表的数据信息
# 方案二：将秘钥加入启动参数 -Djasypt.encryptor.password=xxx
jasypt:
  encryptor:
    password: phoenix
spring:
  # 数据源配置
  datasource:
    username: root
    password: ENC(PfDPA+y3YVDqtcZ0XvkPjL6AYJse5+da)
    url: jdbc:mysql://www.bytes-space.com:10307/dream_blog_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver