server:
  port: 8645
  servlet:
    context-path: /product
eureka:
  client:
    registerWithEureka: true # 服务注册，true表示将自已注册到Eureka服务中
    fetchRegistry: true # 服务发现，true表示从Eureka服务中获取注册信息
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://localhost:6001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,页面会显示主机名
    preferIpAddress: true # 访问路劲可以显示ip地址

spring:
  application:
    name: product-server # Eureka页面显示
