server:
  port: 8082
  servlet:
    context-path: /

logging:
  level:
    com.example: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.67.89.253:3306/oldpeople_pigxx?useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: centos123qwer
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 10


  application:
    name: consumer-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
    # 发现服务的时长间隔
    registry-fetch-interval-seconds: 30

# ribbon配置某一个服务的轮询规则
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# hystrix配置统一的请求超时时间
hystrix:
  command:
    default:
      execution:
       isolation:
        thread:
         timeoutInMilliseconds: 10000

# feign集成ribbon之后的ribbon超时时长配置
ribbon:
  # 读取请求的超时时长
  ReadTimeout: 3000
  # 建立连接的超时时长
  ConnectTimeout: 1000

# feign集成了hystrix  hystrix默认在feign是禁用的 需要在feign开启hystrix
feign:
  hystrix:
    enabled: true
  compression:
    request:
      # 默认false 开启请求压缩
      enabled: true
      # 默认text/html,application/xml,application/json
      mime-types: text/html,application/xml,application/json # 设置压缩的数据类型
      min-request-size: 2048 # 设置触发压缩的大小下限
    response:
      enabled: true # 开启响应压缩
