server:
  port: 9001

spring:
  thymeleaf:
    cache: false
  application:
    name: sso-client1
security:
  oauth2:
    client:
      client-id: client1 # 当前客户端id，对应表oauth_client_details中的id
      client-secret: pc-secret # 客户端密钥，对应表oauth_client_details中的client_secret
      user-authorization-uri: http://localhost:7001/auth/oauth/authorize # 请求认证的地址，获取授权码地址 http://localhost:8643/auth/oauth/authorize
      access-token-uri: http://localhost:7001/auth/oauth/token # 请求令牌的地址 http://localhost:8643/auth/oauth/token
    resource:
      jwt:
        # 当用户授权之后会响应一个授权码，重定向到当前应用的 http://localhost:9001/login?code=xxxxx
        # 自动的会对/login去获取令牌，获取到令牌后会通过key-uri 获取到的公钥进行解密然后本地身份认证和授权（然后通过Session管理）
        # 该路径会获取公钥
        key-uri: http://localhost:7001/auth/oauth/token_key # 该路径需要在认证服务器中进行开放：security.tokenKeyAccess("permitAll()"); http://localhost:8643/auth/oauth/token_key

eureka:
  client:
    registerWithEureka: true # 服务注册，true表示将自已注册到Eureka服务中
    fetchRegistry: true # 服务发现，true表示从Eureka服务中获取注册信息
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://localhost:6001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,页面会显示主机名
    preferIpAddress: true # 访问路劲可以显示ip地址