server:
  port: 9090
  servlet:
    context-path: /

logging:
  level:
    com.example: debug

minio:
  url: http://47.99.113.229:9000/
  access-key: UNTOITMCRVF2F0751RFZ
  secret-key: klMfGG1Plp2Rmswly5Ka4A84LoX7bR1oVH9LIRaD
  endpoint:
    enable: true


spring:
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件大小
      max-request-size: 100MB # 设置总上传的数据大小
      enabled: true #开启
  application:
    name: minio

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#      发现服务的时长间隔
    registry-fetch-interval-seconds: 30



