package com.phoenix.education.mapper;

import com.phoenix.education.model.SalaryDetail;
import com.phoenix.education.model.SalaryDetailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SalaryDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Wed Sep 25 23:39:27 CST 2019
     */
    int countByExample(SalaryDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Wed Sep 25 23:39:27 CST 2019
     */
    int deleteByExample(SalaryDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Wed Sep 25 23:39:27 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Wed Sep 25 23:39:27 CST 2019
     */
    int insert(SalaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Wed Sep 25 23:39:27 CST 2019
     */
    int insertSelective(SalaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Wed Sep 25 23:39:27 CST 2019
     */
    List<SalaryDetail> selectByExample(SalaryDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Wed Sep 25 23:39:27 CST 2019
     */
    SalaryDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Wed Sep 25 23:39:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalaryDetail record, @Param("example") SalaryDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Wed Sep 25 23:39:27 CST 2019
     */
    int updateByExample(@Param("record") SalaryDetail record, @Param("example") SalaryDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Wed Sep 25 23:39:27 CST 2019
     */
    int updateByPrimaryKeySelective(SalaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Wed Sep 25 23:39:27 CST 2019
     */
    int updateByPrimaryKey(SalaryDetail record);
}